-- Generated by generate_supabase_schema.py
-- Table: db_zamereni
create table if not exists db_zamereni (
  -- Surrogate primary key for internal use
  id uuid primary key default gen_random_uuid(),
  sheet_id text,  -- ID - unikátní klíč
  datum_prijeti_leadu timestamptz,  -- Datum přijetí leadu
  kdo_domluvil jsonb,  -- Kdo domluvil
  navolani date,  -- Navolání
  rd_byt rd_byt,  -- RD/Byt
  dopadl_hovor dopadl_hovor,  -- dopadl hovor
  duvod_ne duvod_ne,  -- důvod ne
  komentar_k_hovoru text,  -- komentář k hovoru
  chatbot chatbot,  -- Chatbot
  email text,  -- EMAIL
  telefonni_cislo text,  -- telefonní číslo
  id_web text,  -- ID
  reklama reklama,  -- Reklama
  gclid text,  -- GCLID
  fclid text,  -- FCLID
  prichozi_linka boolean,  -- Příchozí linka?
  dat_prepl_zamer date,  -- dat. přepl. zaměř.
  kdo_prepl_zamer jsonb,  -- Kdo přepl. zaměř.
  dat_zamer date,  -- dat. zaměř.
  cas_zamer time,  -- čas zaměření
  zamerovac jsonb,  -- Zaměřovač
  produkt_zamereni produkt_zamereni[],  -- produkt zaměření
  dopadlo_to dopadlo_to,  -- Dopadlo to ?
  proc_ne_zamereni proc_ne_zamereni,  -- proč ne zaměření
  dokoncil_vytvoril_cn jsonb,  -- dokončil/vytvořil CN
  komentar_k_zamereni_duvod_zruseni_zamereni komentar_k_zamereni_duvod_zruseni_zamereni,  -- Komentář k zaměření - Důvod zrušení zaměření
  datum_vyt_fa date,  -- Datum vyt. FA
  kdo_vyst_fa jsonb,  -- Kdo vyst. FA
  splatnost date,  -- splatnost
  cislo_zalohove_fa text,  -- číslo zálohové FA
  report_zaplaceno text,  -- Report zaplaceno
  predbezna_hodnota numeric(12,2),  -- předběžná hodnota
  platba platba,  -- platba
  montazni_list montazni_list,  -- montážní list
  preplanoval_montaz jsonb,  -- Přeplánoval montáž
  datum_hovoru_preplanovani_montaze date,  -- Datum hovoru přeplánování montáže
  dat_nav_montaze date,  -- dat. nav. montáže
  dat_montaze date,  -- dat. montáže
  cas_montaze time,  -- čas montáže
  monteri jsonb,  -- montér č. 1
  dokoncena_montaz boolean,  -- dokončena montáž?
  proc_ne_vyhrada_montaz proc_ne_vyhrada_montaz,  -- proč ne/výhrada montáž
  kdo_preplanoval_servis jsonb,  -- Kdo přeplanoval servis
  datum_preplanovani_servisu date,  -- Datum přeplánování servisu
  kdo_domlouval_servis jsonb,  -- Kdo domlouval servis
  kdy_domluven_servis date,  -- Kdy domluven servis
  datum_servisu date,  -- Datum servisu
  cas_servisu time,  -- čas servisu
  delka_servisu numeric,  -- délka servisu
  monteri_servis jsonb,  -- montér servis č.1
  dokonceno_servis boolean,  -- dokončeno? servis
  proc_ne_servis text,  -- proč ne? servis
  kdo_preplan_zam jsonb  -- Kdo přeplán/zam.
);

-- Warnings during generation:
--   Unrecognized type '' for column 'report_zaplaceno', defaulting to text.
